name: Caller Workflow Test

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Ambiente de build'
        required: true
        type: choice
        options:
            - producaoCloudPrd
            - pilotoCloudPrd
  push:
    branches:
      - main                          
jobs:
  test:
    uses: brenhe/flow_test/.github/workflows/workflow_call.yaml@main
    with:
        build_type: ${{ inputs.build_type }}     
        