name: Caller Workflow Test

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Ambiente de build'
        required: true
        type: choice
        options:
            - producaoCloudPrd
            - pilotoCloudPrd                
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Call
        uses: brenhe/flow_test/.github/workflows/workflow_call.yaml@main
        with:
          build_type: ${{ inputs.build_type }}     
        