name: Caller Workflow Test

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Ambiente de build'
        required: true
        type: choice
        options:
            - producaoCloudPrd
            - pilotoCloudPrd        

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
            echo "Running tests for build type: ${{ inputs.build_type }}"
        shell: bash     