name: Caller Workflow      

on:
  workflow_call:
    inputs:
      build_type:
        type: string
        description: 'Type of build to run tests for'
        required: true
jobs:
  test:
    uses: brenhe/flow_test/.github/workflows/new_workflow_call.yaml@main
    with:
        build_type: ${{ inputs.build_type }}   