name: Caller Workflow

on:
  workflow_call:
    inputs:
      build_type:
        description: "Type of build to run tests for"
        required: true
        type: string

jobs:
  test:
    uses: brenhe/flow-test/.github/workflows/new_workflow_call.yaml@main
    with:
      build_type: ${{ inputs.build_type }}