name: Caller Workflow

on:
  workflow_call:
    inputs:
      build_type:
        description: "Type of build to run tests for"
        required: true
        type: string

jobs:
  Chamando_New_Workflow_Call:
    uses: brenhe/flow-test/.github/workflows/new_workflow_call.yaml@main
    with:
      build_type: ${{ inputs.build_type }}
  Valor_do_Input_Selecionado:
    runs-on: ubuntu-latest
    steps:
      - name: Run input value test
        run: |
            echo "Running tests for build type: ${{ inputs.build_type }}"
        shell: bash      